# Generated by Django 2.1.2 on 2020-08-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
