# Generated by Django 2.1.2 on 2020-08-09 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiktok_app', '0002_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestVideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile_name', models.CharField(max_length=500, null=True)),
                ('video_file', models.CharField(max_length=500, null=True)),
                ('video_discription', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audiofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiktok_app.AudioFile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
